#!/bin/sh

# TODO check the options are all valid 


# TODO Check we have root permissions and report an error if not
echo You must be \"root\" for install to work correctly

mkdir -p /etc/tagEventor
cp -f generic /etc/tagEventor/
echo Script \"generic\" copied to /etc/tagEventor/

cp -f tagEventor /usr/sbin
echo Executable \"tagEventor\" copied to /usr/sbin/

cp -f tagEventord /etc/init.d
echo Init script \"tagEventord\" copied to /etc/init.d/

cd /etc/init.d
echo Adding init script links to /etc/rc\?.d with update-rc.d
update-rc.d -f tagEventord start 80 2 3 4 5 .
cd -

####### GNOME Specific install options

