#!/bin/sh

# TODO check the options are all valid

# TODO Check we have root permissions and report an error if not
echo You must be \"root\" for install to work correctly
echo ""

###################################################################################
# make sure we have all the (correct) binaries built
make cleanRelease Release

############################################### tagEventor  #######################
# Copy the generic script that is used when no specific script is found for the tag ID
echo "Installing tag event scripts"
mkdir -p /etc/tagEventor
cp -f scripts/generic /etc/tagEventor/
echo Script \"./scripts/generic\" copied to /etc/tagEventor/
echo ""

# copy the tageventor binary to the system directory
echo "Installing the Program Binary"
cp -f bin/Release/tagEventor /usr/sbin
echo Executable \"./bin/Release/tagEventor\" copied to /usr/sbin/
echo ""

####### DAEMON specific install options
# copy the init script to the system directory so that tag eventor will be started as a daemon
# TODO once we merge binaries and have a GNOME item running, this could be removed or disabled.
echo "Installing daemon start-up script "
cp -f tagEventord /etc/init.d
echo Init script \"./tagEventord\" copied to /etc/init.d/
echo ""

# to have the init script actually run at start-up you need these links in the system directories
cd /etc/init.d
echo Adding init script links to /etc/rc\?.d with update-rc.d
update-rc.d -f tagEventord start 80 2 3 4 5 .
cd -
echo ""

############################################## gtagEventor  #######################
# copy the gtagEventor binary to the system directory
echo "Installing the Program Binary"
cp -f bin/Release/gtagEventor /usr/sbin
echo Executable \"./bin/Release/gtagEventor\" copied to /usr/sbin/
echo ""

# put a desktop link in the right place and it will start executable with each GNOME session
# TODO when we merge binaries, this may need changing. At the moment it starts the cpanel binary.
echo "Installing Gnome start-up entries"
cp gtagEventor.desktop /etc/xdg/autostart/
echo ./gtagEventor.desktop copied into "/etc/xdg/autostart/" so it is started with each GNOME session
echo ""

# copy the required icons to a place where GNOME can find them without .svn directories!
# delete older icons first
rm -rf /usr/share/gtagEventor/icons/hicolor/*

echo "Installing icons"
# NOTE: This path is also in the code, so if you change one, change both
# This one is a temporary fix
mkdir -p /usr/share/gtagEventor/icons/
cp -R ./icons/*.png /usr/share/tagEventor/icons/

mkdir -p /usr/share/gtagEventor/icons/hicolor/16x16
cp -R ./icons/hicolor/16x16/*.png /usr/share/tagEventor/icons/hicolor/16x16/

mkdir -p /usr/share/gtagEventor/icons/hicolor/22x22
cp -R ./icons/hicolor/22x22/*.png /usr/share/tagEventor/icons/hicolor/22x22/

mkdir -p /usr/share/gtagEventor/icons/hicolor/32x32
cp -R ./icons/hicolor/32x32/*.png /usr/share/tagEventor/icons/hicolor/32x32/

mkdir -p /usr/share/gtagEventor/icons/hicolor/48x48
cp -R ./icons/hicolor/48x48/*.png /usr/share/tagEventor/icons/hicolor/48x48/

mkdir -p /usr/share/gtagEventor/icons/hicolor/64x64
cp -R ./icons/hicolor/64x64/*.png /usr/share/tagEventor/icons/hicolor/64x64/

mkdir -p /usr/share/gtagEventor/icons/hicolor/128x128
cp -R ./icons/hicolor/128x128/*.png /usr/share/tagEventor/icons/hicolor/128x128/

echo Copied ./icons/ into "/usr/share/gtagEventor"
echo ""
