#!/bin/sh

# TODO check the options are all valid

# TODO Check we have root permissions and report an error if not
echo You must be \"root\" for install to work correctly
echo ""

# Copy the generic script that is used when no specific script is found for the tag ID
echo "Installing tag event scripts"
mkdir -p /etc/tagEventor
cp -f scripts/generic /etc/tagEventor/
echo Script \"./scripts/generic\" copied to /etc/tagEventor/
echo ""

# copy the tageventor binaries to the system directory
# TODO change make to build a release binary and install it instead
echo "Installing the Program Binary"
cp -f bin/Release/tagEventor /usr/sbin
echo Executable \"./bin/Release/tagEventor\" copied to /usr/sbin/
echo ""

####### DAEMON specific install options
# copy the init script to the system directory so that tag eventor will be started as a daemon
# TODO once we merge binaries and have a GNOME item running, this could be removed or disabled.
echo "Installing daemon start-up script "
cp -f tagEventord /etc/init.d
echo Init script \"./tagEventord\" copied to /etc/init.d/
echo ""

# to have the init script actually run at start-up you need these links in the system directories
cd /etc/init.d
echo Adding init script links to /etc/rc\?.d with update-rc.d
update-rc.d -f tagEventord start 80 2 3 4 5 .
cd -
echo ""

####### GNOME Specific install options
# put a desktop link in the right place and it will start executable with each GNOME session
# TODO when we merge binaries, this may need changing. At the moment it starts the cpanel binary.
echo "Installing Gnome start-up entries"
cp tagEventor.desktop /etc/xdg/autostart/
echo ./tagEventor.desktop copied into "/etc/xdg/autostart/" so it is started with each GNOME session
echo ""

# copy the required icons to a place where GNOME can find them
echo "Installing icons"
cp icons/*.png /usr/share/app-install/icons/
echo Copied ./icons/\*.png into "/usr/share/app-install/icons/"
echo ""
