#!/bin/sh
# Example tag event script for tagEventor from autelic
# See http://www.autelic.org for more on autelic
# See http://code.google.com/p/tc-squared for more on tagEventor
# parameters passed are:
# $1 = SAM (unique ID of the SAM chip in the smart card reader if exists, 0 otherwise
# $2 = UID (unique ID of the tag, as later we may use wildcard naming)
# $3 = Event Type (IN for new tag placed on reader, OUT for tag removed from reader)

# open the desired web page in a new opera browser if none running, or existing
# instance and active tab if one is running
if [[ $3 = "IN" ]]
then
   /usr/bin/opera -activetab http://www.autelic.org?sam=$1\&uid=$2\&type=$3&
else
   exit 0
fi
