#!/bin/bash
if [[ $3 = "IN" ]]
then
   # get the pid of all instances of opera running, use ´h´ to not show a header for each column
   pids=`ps -C opera -o pid h`
   for pid in $pids
   do
      /bin/kill -9 $pid 2>&1 &> /dev/null
   done
else
   exit 0
fi
